name: CD Artifacts
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Simulando CD
        run: mkdir -p artifact
        run: echo hello > artifact/world.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifact/world.txt
