name: CD Artifacts
on:
  push:
    branches:
      - main

jobs:
  # deliver:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Simulando CD
  #       run: |
  #         mkdir -p artifact
  #         echo hello > artifact/world.txt

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: my-artifact
  #         path: artifact/world.txt

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: deliver
  #   steps:
  #     - name: Simulando Deploy
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: my-artifact
  #     - name: Display structure of downloaded files
  #       run: ls -R
