name: ci-docker

on:
  pull_request:
    branch:
      - main
      - develop

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
